{
  "formatVersion": "1.1",
  "component": {
    "group": "biq.sdk.android",
    "module": "biq",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.17.aar",
          "url": "biq-1.0.17.aar",
          "size": 413538,
          "sha512": "bd15b00ccf44ba02490b4d576091a2129a65e4da9dfd374ba562ccef7cd2d39b3577c7565acb6545822c0e0ebbe2e72deb6fe6822bd5876279e89940024d949f",
          "sha256": "55129e03dde10fa8be4d74679d47938a9297d3bfb93a9f58e1bbf245d0c92f71",
          "sha1": "e5c45c56e46e1b94135513a624f268ce5856c3cb",
          "md5": "c67f81f90f062c86a04eb4dde550212e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.17.aar",
          "url": "biq-1.0.17.aar",
          "size": 413538,
          "sha512": "bd15b00ccf44ba02490b4d576091a2129a65e4da9dfd374ba562ccef7cd2d39b3577c7565acb6545822c0e0ebbe2e72deb6fe6822bd5876279e89940024d949f",
          "sha256": "55129e03dde10fa8be4d74679d47938a9297d3bfb93a9f58e1bbf245d0c92f71",
          "sha1": "e5c45c56e46e1b94135513a624f268ce5856c3cb",
          "md5": "c67f81f90f062c86a04eb4dde550212e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biq-1.0.17-sources.jar",
          "url": "biq-1.0.17-sources.jar",
          "size": 48069,
          "sha512": "d5c4aac8e7191409a6ce8b76249907f9b5c1f45658394c91437b93a6e84b0982d07c5cfcb55645c2a7f8eff94ff4b8f3c683a748e25848091d52b4c5dd798ee9",
          "sha256": "1c0358a3d71308c3ca8ab0fb4341ba1736c154a77b17f209b21407ded371b977",
          "sha1": "eac03eb1b128807831ea197c8b5c40c3d05a886a",
          "md5": "e0812e46b8d8012eda12f8c8647f38bd"
        }
      ]
    }
  ]
}
