{
  "formatVersion": "1.1",
  "component": {
    "group": "biq.sdk.android",
    "module": "biq",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.21.aar",
          "url": "biq-1.0.21.aar",
          "size": 432873,
          "sha512": "954de20a74656c504a071981c334502607c287b14cf228931a85e916c8b522db9589c6d4300560e7f78aa638054158b0fde92f2d11fcbe625514cb3fda53f5fb",
          "sha256": "5c4b8216aa3a465099825d399593e9fa97786d952e433b32463fa916772075af",
          "sha1": "8bf8622951c10d7b17b756b289754796157e3530",
          "md5": "9d518cd57500b6159e26c870776245d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.21.aar",
          "url": "biq-1.0.21.aar",
          "size": 432873,
          "sha512": "954de20a74656c504a071981c334502607c287b14cf228931a85e916c8b522db9589c6d4300560e7f78aa638054158b0fde92f2d11fcbe625514cb3fda53f5fb",
          "sha256": "5c4b8216aa3a465099825d399593e9fa97786d952e433b32463fa916772075af",
          "sha1": "8bf8622951c10d7b17b756b289754796157e3530",
          "md5": "9d518cd57500b6159e26c870776245d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biq-1.0.21-sources.jar",
          "url": "biq-1.0.21-sources.jar",
          "size": 52501,
          "sha512": "16ecd222e88aa554b534902c52f998a4ef4dd17388b517345f52110c268b14d2c6d38253f5bfab0c125ce3beb0c48ba1b2a355591bf3b8f1e3d38b624388f487",
          "sha256": "de1e399d62bc57bccc74d1c0161d622c6362006bfb0d46bc1b21753f45b4a754",
          "sha1": "c698bad5a737925b6c9d0c56bd93a11de8538c41",
          "md5": "0d3b03d60288aeac75a4db8dd0403b02"
        }
      ]
    }
  ]
}
