{
  "formatVersion": "1.1",
  "component": {
    "group": "biq.sdk.android",
    "module": "biq",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.12.aar",
          "url": "biq-1.0.12.aar",
          "size": 357981,
          "sha512": "b8c9d636989da96b554a8c158425e58872a80bfa79176d6be9677a2703591295eb0a3e190007cbe329335b38177089a32123f99e452942fdc1edc577a8db7983",
          "sha256": "d7e5df1b24b2c4bd1a87afcf08ec8d55ee38db86be4deac09fcbb3f1b59bd804",
          "sha1": "d6c4f63499d3ab6f30c16b155cf54a5e584b2cbb",
          "md5": "dd5ab9d89fcedc82c446030fd3467223"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.12.aar",
          "url": "biq-1.0.12.aar",
          "size": 357981,
          "sha512": "b8c9d636989da96b554a8c158425e58872a80bfa79176d6be9677a2703591295eb0a3e190007cbe329335b38177089a32123f99e452942fdc1edc577a8db7983",
          "sha256": "d7e5df1b24b2c4bd1a87afcf08ec8d55ee38db86be4deac09fcbb3f1b59bd804",
          "sha1": "d6c4f63499d3ab6f30c16b155cf54a5e584b2cbb",
          "md5": "dd5ab9d89fcedc82c446030fd3467223"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biq-1.0.12-sources.jar",
          "url": "biq-1.0.12-sources.jar",
          "size": 42749,
          "sha512": "80d5d028dd8388767eac1eb133257cf431c44480d2598aef5fe1cdf417f01eb9f37a19043fff5e234c04a968e1a21f3d6deb074079fff5214bde61834e8d55f6",
          "sha256": "d9f91ef329f16ab2b7dbeaea25286461743af089ac984c884ccb2f13c9664010",
          "sha1": "92ab1e526ebf069c96a5de30d03ad31843b68eca",
          "md5": "3d3f338b069f5d917148383cbeb529f7"
        }
      ]
    }
  ]
}
