{
  "formatVersion": "1.1",
  "component": {
    "group": "biq.sdk.android",
    "module": "biq",
    "version": "1.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.23.aar",
          "url": "biq-1.0.23.aar",
          "size": 435830,
          "sha512": "d27a0483a400620f286056b2854808d12f2aceba65d8fdbeabef0f5b774782d77c421a77bc3f0110a80857745a1e68c2d90684b2b6572403cd8b7458454fadd0",
          "sha256": "aad2bfd58033acaafa1e5b7771270c807ed5c7130625882b783d6dc7f164fb61",
          "sha1": "208e829f8df0aa96d9608fcea2a853cdf66e1711",
          "md5": "10d6f932b9d5687e9dd973eddbab6992"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.23.aar",
          "url": "biq-1.0.23.aar",
          "size": 435830,
          "sha512": "d27a0483a400620f286056b2854808d12f2aceba65d8fdbeabef0f5b774782d77c421a77bc3f0110a80857745a1e68c2d90684b2b6572403cd8b7458454fadd0",
          "sha256": "aad2bfd58033acaafa1e5b7771270c807ed5c7130625882b783d6dc7f164fb61",
          "sha1": "208e829f8df0aa96d9608fcea2a853cdf66e1711",
          "md5": "10d6f932b9d5687e9dd973eddbab6992"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biq-1.0.23-sources.jar",
          "url": "biq-1.0.23-sources.jar",
          "size": 53778,
          "sha512": "f8ffcfd25a527741147a648a0a09c5c78f5398099bddfda684399d4a98bf300c7402f22359437d5eafb99697b8f3978992aff5b06b23c4c5b9f6e58567af1582",
          "sha256": "eb0b198badf08131a291d4099a86313f0e4c83dcb6102a725300b4e3d923234b",
          "sha1": "750216aec709bad4a931a076d6d42197fbabe132",
          "md5": "bc1df3947cc4307a80114e045e6fb6e6"
        }
      ]
    }
  ]
}
