{
  "formatVersion": "1.1",
  "component": {
    "group": "biq.sdk.android",
    "module": "biq",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.7.aar",
          "url": "biq-1.0.7.aar",
          "size": 350474,
          "sha512": "0bd9768adc7fdc40b0e3811c558c1ad0fd026ca42e87d75510bf6221c28185fc1f7f101ab9a0d8e296d0c863edb3f66ccc36f6d297670d63469cf3ff85d11bab",
          "sha256": "0eec04541de2828d5172b2c9b62a813ba299b1e6bc40c6c59d4713e21003aff0",
          "sha1": "662136e1feb3145204034c57ef574394ff901ea6",
          "md5": "696eec5aa758bdda0fb548a5acf47fc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.davidgyoungtech",
          "module": "beacon-parsers",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "org.altbeacon",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "biq-1.0.7.aar",
          "url": "biq-1.0.7.aar",
          "size": 350474,
          "sha512": "0bd9768adc7fdc40b0e3811c558c1ad0fd026ca42e87d75510bf6221c28185fc1f7f101ab9a0d8e296d0c863edb3f66ccc36f6d297670d63469cf3ff85d11bab",
          "sha256": "0eec04541de2828d5172b2c9b62a813ba299b1e6bc40c6c59d4713e21003aff0",
          "sha1": "662136e1feb3145204034c57ef574394ff901ea6",
          "md5": "696eec5aa758bdda0fb548a5acf47fc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biq-1.0.7-sources.jar",
          "url": "biq-1.0.7-sources.jar",
          "size": 40674,
          "sha512": "94faea6a0ec68d12e8fa945efba7850071bdf4505b594b6e8888b6d9689f516e1f92b670bbcb03d85f6f603e735f3ff8d3347d2d44275c200e405f1f8369934c",
          "sha256": "344aaf2bab62ac38f2a88e31495726bfcf977faee59c794620f6383940623e4a",
          "sha1": "cd9d4ae1586d0f96dc4fcefb7b98461d61ff2d67",
          "md5": "c9db869645762cd1b8ab60bcd67fd798"
        }
      ]
    }
  ]
}
